# Generated by Django 5.1 on 2024-09-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=200, verbose_name='Субъект')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
            ],
        ),
    ]
